//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class arriendo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arriendo()
        {
            this.detalle_arriendo = new HashSet<detalle_arriendo>();
        }
    
        public int crr_arriendo { get; set; }
        public System.DateTime fec_arriendo { get; set; }
        public System.DateTime fec_devolucion { get; set; }
        public System.DateTime fec_devolucionefectiva { get; set; }
        public short estado_arriendo_cod_estado { get; set; }
        public int subtotal { get; set; }
        public int iva { get; set; }
        public short cuotas { get; set; }
        public int vuelto { get; set; }
        public int medio_pago_cod_mediopago { get; set; }
        public int usuario_persona_rut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_arriendo> detalle_arriendo { get; set; }
    }
}
