//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedido
    {
        public int producto_cod_producto { get; set; }
        public int pedido_crr_pedido { get; set; }
        public int cantidad { get; set; }
        public int subtotal { get; set; }
        public int iva { get; set; }
        public int total { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual producto producto { get; set; }
    }
}
