//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ejecucion_servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ejecucion_servicio()
        {
            this.detalle_ventaservicio = new HashSet<detalle_ventaservicio>();
        }
    
        public int crr_servicio { get; set; }
        public System.DateTime fec_ejecucion { get; set; }
        public int rut1 { get; set; }
        public int rut2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ventaservicio> detalle_ventaservicio { get; set; }
        public virtual estado_servicio estado_servicio { get; set; }
        public virtual operador operador { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
