//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Bicicleta
    {
        public int id_pedido { get; set; }
        public Nullable<System.DateTime> fec_pedido { get; set; }
        public Nullable<int> subtotal { get; set; }
        public Nullable<int> iva { get; set; }
        public int total { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    }
}
