//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public long id_stock { get; set; }
        public Nullable<int> bodega_cod_bodega { get; set; }
        public Nullable<int> producto_cod_producto { get; set; }
        public Nullable<int> actual { get; set; }
        public Nullable<int> minimo { get; set; }
    }
}
