//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int persona_rut { get; set; }
        public string pass { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
