//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ventaservicio
    {
        public int ejecucion_servicio_crr_servicio { get; set; }
        public int venta_crr_venta { get; set; }
        public int cantidad { get; set; }
        public int subtotal { get; set; }
        public int iva { get; set; }
        public Nullable<int> total { get; set; }
        public int descuento { get; set; }
    
        public virtual ejecucion_servicio ejecucion_servicio { get; set; }
    }
}
