//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_arriendo
    {
        public int producto_cod_producto { get; set; }
        public int arriendo_crr_arriendo { get; set; }
        public int cantidad { get; set; }
        public int subtotal { get; set; }
        public int iva { get; set; }
        public int total { get; set; }
        public int descuento { get; set; }
    
        public virtual arriendo arriendo { get; set; }
        public virtual producto producto { get; set; }
    }
}
