//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterBikesEntities : DbContext
    {
        public MasterBikesEntities()
            : base("name=MasterBikesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arriendo> arriendo { get; set; }
        public virtual DbSet<bodega> bodega { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<detalle_arriendo> detalle_arriendo { get; set; }
        public virtual DbSet<detalle_pedido> detalle_pedido { get; set; }
        public virtual DbSet<detalle_ventaproducto> detalle_ventaproducto { get; set; }
        public virtual DbSet<detalle_ventaservicio> detalle_ventaservicio { get; set; }
        public virtual DbSet<ejecucion_servicio> ejecucion_servicio { get; set; }
        public virtual DbSet<estado_arriendo> estado_arriendo { get; set; }
        public virtual DbSet<estado_servicio> estado_servicio { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<medio_pago> medio_pago { get; set; }
        public virtual DbSet<operador> operador { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_proveedor> producto_proveedor { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<tipo_producto> tipo_producto { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<ArriendoBicicleta> ArriendoBicicleta { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<Pedido_Bicicleta> Pedido_Bicicleta { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<ServicioBicicleta> ServicioBicicleta { get; set; }
    }
}
