//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOC.Integracion.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_proveedor
    {
        public int producto_cod_producto { get; set; }
        public string proveedor_id_proveedor { get; set; }
        public System.DateTime fec_iniciocontrato { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public short flg_activo { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
